---
# Determine a Repo in your Org to provide 'client-side rules' (located under `.github/rules/`)
# ------------------------------------------------------------
# If server-side rules are provided, they will always be applied. 'server-side rules' cannot be modified by users!
# `repo name`: The name of the Repo in your Org that contains the client-side rules
# `.`: The App will look for client-side rules in the Repo that triggerred the event ('local' client-side rule)
# `none`: No client-side rules will be applied, only 'server-side rules' will be applied
# Options: `Repo name`, `.` or `none` 
rules_repo: none

# This is a "Lazy Refresh". We only check on an incoming event, if the interval expired.
# The reload interval for client-side rules, in minutes.
rules_refreshInterval: 1